const itemDictData = {
    'sanguine_reaper':{Name:'Sanguine Reaper', Price:'300', Type:'Weapon', Desc:'A two-handed weapon that deals physical damage. Has a greater effect on undead.'},
    'sanguine_crossbow':{Name:'Sanguine Crossbow', Price:'300', Type:'Weapon', Desc:'A ranged Weapon that fires bolts.'},
    'dark_silver_slashers':{Name:'Dark Silver Slasher', Price:'200', Type:'Weapon', Desc:'Dual-wield blades that deal slash damage. Has a physical damage bonus to vegetation and thickets.'},
    'dark_silver_pistols':{Name:'Dark Silver Pistols', Price:'200', Type:'Weapon', Desc:'Black-powder weapons effective at medium range.'},
    'iron_sword':{Name:'Iron Sword', Price:'100', Type:'Weapon', Desc:'An all-round Weapon that deals slash damage. Has a physical damage bonus to vegetation and thickets.'},
    'iron_mace':{Name:'Iron Mace', Price:'100', Type:'Weapon', Desc:'A heavy Weapon that deals blunt damage. Has a physical damage bonus to minerals.'},
    'copper_spear':{Name:'Copper Spear', Price:'50', Type:'Weapon', Desc:'An long-ranged Weapon that deals thrust damage in a line. Has a physical damage bonus to creatures.'},
    'copper_axes':{Name:'Copper Axes', Price:'50', Type:'Weapon', Desc:'Dual-wield axes that deal chop damage. Has a physical damage bonus to wood.'},
    
    'blood_key':{Name:'Blood Key', Price:'400', Type:'Equipment', Desc:'Increases spellpower.'},
    'blood_merlot_amulet':{Name:'Blood Merlot Amulet', Price:'300', Type:'Equipment', Desc:'Increases spellpower.'},
    'ring_of_the_warlock':{Name:'Ring of the Warlock', Price:'200', Type:'Equipment', Desc:'Increases spellpower.'},
    'gravedigger_ring':{Name:'Gravedigger Ring', Price:'100', Type:'Equipment', Desc:'Increases spellpower.'},
    'cardinals_cloak':{Name:'Cardinal Cloak', Price:'250', Type:'Equipment', Desc:'Provides various resistances.'},
    'beatrices_scarf':{Name:"Beatrice's Scarf", Price:'250', Type:'Equipment', Desc:'Provides various resistances.'},
    'crimson_ward':{Name:'Crimson Ward', Price:'250', Type:'Equipment', Desc:'Provides various resistances.'},
    'royal_veil_of_the_jester':{Name:'Royal Veil Of The Jester', Price:'250', Type:'Equipment', Desc:'Provides various resistances.'},
    'tail_of_the_archfiend':{Name:'Tail Of The Archfiend', Price:'250', Type:'Equipment', Desc:'Provides various resistances.'},
    'plague_doctor_mask':{Name:'Plague Doctor Mask', Price:'300', Type:'Equipment', Desc:'Differentiate yourself from other vampires with this stylish headgear.'},
    'immortal_kings_greathelm':{Name:"Immortal King's Greathelm", Price:'300', Type:'Equipment', Desc:'Differentiate yourself from other vampires with this stylish headgear.'},
    'razer_hood':{Name:'Razer Hood', Price:'300', Type:'Equipment', Desc:'Differentiate yourself from other vampires with this stylish headgear.'},
    
    'flawless_sapphire':{Name:'Flawless Sapphire', Price:'75', Type:'Gem', Desc:'Reagent used for crafting.'},
    'flawless_emerald':{Name:'Flawless Emerald', Price:'75', Type:'Gem', Desc:'Reagent used for crafting.'},
    'regular_miststone':{Name:'Regular Mistsone', Price:'50', Type:'Gem', Desc:'Reagent used for crafting.'},
    'regular_topaz':{Name:'Regular Topaz', Price:'50', Type:'Gem', Desc:'Reagent used for crafting.'},
    'crude_ruby':{Name:'Crude Ruby', Price:'25', Type:'Gem', Desc:'Reagent used for crafting.'},

    'blood_rose_potion':{Name:'Blood Rose Potion', Price:'30', Type:'Consumable', Desc:'A potion that recovers health every 1 seconds for 15 seconds. '},
    'potion_of_rage':{Name:'Potion of Rage', Price:'30', Type:'Consumable', Desc:'A brew that increases physical power for 1200 seconds.'},
    'silver_resistance_potion':{Name:'Silver Resistance Potion', Price:'40', Type:'Consumable', Desc:'A potion that increases silver resistance rating for 1800 seconds.'},
    'garlic_resistance_potion':{Name:'Garlic Resistance Potion', Price:'40', Type:'Consumable', Desc:'A potion that increases garlic resistance rating for 1800 seconds.'},
    'holy_resistance_flask':{Name:'Holy Resistance Flask', Price:'40', Type:'Consumable', Desc:'A potion that increases holy resistance rating for 1800 seconds.'},
    'dusk_caller':{Name:'Dusk Caller', Price:'150', Type:'Consumable', Desc:'Summon a swarm of bats to transport a subdued human back to the nearest unoccupied prison cell within your realm.'},
    
    'thick_leather':{Name:'Thick Leather', Price:'20', Type:'Resource', Desc:'Reagent used for crafting.'},
    'leather':{Name:'Leather', Price:'10', Type:'Resource', Desc:'Reagent used for crafting.'},
    'thick_hide':{Name:'Thick Hide', Price:'10', Type:'Resource', Desc:'Reagent used for crafting.'},
    'rugged_hide':{Name:'Rugged Hide', Price:'5', Type:'Resource', Desc:'Reagent used for crafting.'},
    'clay':{Name:'Clay', Price:'5', Type:'Resource', Desc:'Reagent used for crafting.'},
    'stone_brick':{Name:'Stone Brick', Price:'10', Type:'Resource', Desc:'Reagent used for crafting.'},
    'stone':{Name:'Stone', Price:'5', Type:'Resource', Desc:'Reagent used for crafting.'},
    'reinforced_plank':{Name:'Reinforced Plank', Price:'20', Type:'Resource', Desc:'Reagent used for crafting.'},
    'plank':{Name:'Plank', Price:'10', Type:'Resource', Desc:'Reagent used for crafting.'},
    'wood':{Name:'Wood', Price:'5', Type:'Resource', Desc:'Reagent used for crafting.'},
}

export { itemDictData }